void blink_light(byte pin, int delay_ms);
void print_and_blink_light(byte pin, char *message);
void blank_line();
void debug_print(char *message);
void generate_battery_report(char *buff);
long read_vcc();
void send_data_proto(char *message, int gateway_id, char *node_name, int led_pin);
void setup_serial(int speed);
void setup_radio(int node_id, int network_id, char *encrypt_key);
void sleep();
